apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment
  labels:
    app: shoppingclient
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
        - name: shoppingclient
          image: sekarshoppingacr.azurecr.io/shoppingclient:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: shoppingapi-configmap
                    key: shoppingapi_url

---
apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-service
spec:
  type: LoadBalancer
  selector:
    app: shoppingclient
  ports:
    - protocol: TCP
      port: 80           