apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingdb
  template:
    metadata:
      labels:
        app: shoppingdb
    spec:
      containers:
      - name: shoppingdb
        image: mongo
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingdb
spec:
  ports:
  - port: 27017
  selector:
    app: shoppingdb