version: '3.4'

services:
  shopping.api:
    image: sekarfeb/shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

  shopping.client:
    image: sekarfeb/shoppingclient
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile

  shopping.db:
    image: mongo